"use strict";

const name = "safari:10";

const spec = {
  "/AudioContext": { "global": "webkitAudioContext" },
  "/AudioContext/activeSourceCount": { "deprecated": true },
  "/AudioContext/close": {},
  "/AudioContext/createAnalyser": {},
  "/AudioContext/createBiquadFilter": {},
  "/AudioContext/createBuffer": {},
  "/AudioContext/createBufferSource": {},
  "/AudioContext/createChannelMerger": {},
  "/AudioContext/createChannelSplitter": {},
  "/AudioContext/createConvolver": {},
  "/AudioContext/createDelay": {},
  "/AudioContext/createDelayNode": { "deprecated": true },
  "/AudioContext/createDynamicsCompressor": {},
  "/AudioContext/createGain": {},
  "/AudioContext/createGainNode": { "deprecated": true },
  "/AudioContext/createJavaScriptNode": { "deprecated": true },
  "/AudioContext/createMediaElementSource": {},
  "/AudioContext/createOscillator": {},
  "/AudioContext/createPanner": {},
  "/AudioContext/createPeriodicWave": {},
  "/AudioContext/createScriptProcessor": {},
  "/AudioContext/createWaveShaper": {},
  "/AudioContext/currentTime": {},
  "/AudioContext/decodeAudioData": { "void": true },
  "/AudioContext/destination": {},
  "/AudioContext/listener": {},
  "/AudioContext/oncomplete": {},
  "/AudioContext/onstatechange": {},
  "/AudioContext/resume": {},
  "/AudioContext/sampleRate": {},
  "/AudioContext/startRendering": { "void": true },
  "/AudioContext/state": {},
  "/AudioContext/suspend": {},

  "/OfflineAudioContext": { "global": "webkitOfflineAudioContext" },

  "/AudioNode": { "global": "AudioNode", "protected": true },
  "/AudioNode/channelCount": {},
  "/AudioNode/channelCountMode": {},
  "/AudioNode/channelInterpretation": {},
  "/AudioNode/connect": { "void": true },
  "/AudioNode/context": {},
  "/AudioNode/disconnect": { "selective": false },
  "/AudioNode/numberOfInputs": {},
  "/AudioNode/numberOfOutputs": {},

  "/AudioDestinationNode": { "global": "AudioDestinationNode", "protected": true },
  "/AudioDestinationNode/maxChannelCount": {},

  "/AudioParam": { "global": "AudioParam", "protected": true },
  "/AudioParam/cancelScheduledValues": { "void": true },
  "/AudioParam/defaultValue": {},
  "/AudioParam/exponentialRampToValueAtTime": { "void": true },
  "/AudioParam/linearRampToValueAtTime": { "void": true },
  "/AudioParam/maxValue": {},
  "/AudioParam/minValue": {},
  "/AudioParam/name": { "deprecated": true },
  "/AudioParam/setTargetAtTime": { "void": true },
  "/AudioParam/setTargetValueAtTime": { "void": true },
  "/AudioParam/setValueAtTime": { "void": true },
  "/AudioParam/setValueCurveAtTime": { "void": true },
  "/AudioParam/units": { "deprecated": true },
  "/AudioParam/value": {},

  "/GainNode": { "global": "GainNode", "protected": true },
  "/GainNode/gain": {},

  "/DelayNode": { "global": "DelayNode", "protected": true },
  "/DelayNode/delayTime": {},

  "/AudioBuffer": { "global": "AudioBuffer", "protected": true },
  "/AudioBuffer/duration": {},
  "/AudioBuffer/gain": { "deprecated": true },
  "/AudioBuffer/getChannelData": {},
  "/AudioBuffer/length": {},
  "/AudioBuffer/numberOfChannels": {},
  "/AudioBuffer/sampleRate": {},

  "/AudioBufferSourceNode": { "global": "AudioBufferSourceNode", "protected": true },
  "/AudioBufferSourceNode/FINISHED_STATE": { "deprecated": true },
  "/AudioBufferSourceNode/PLAYING_STATE": { "deprecated": true },
  "/AudioBufferSourceNode/SCHEDULED_STATE": { "deprecated": true },
  "/AudioBufferSourceNode/UNSCHEDULED_STATE": { "deprecated": true },
  "/AudioBufferSourceNode/buffer": {},
  "/AudioBufferSourceNode/gain": { "deprecated": true },
  "/AudioBufferSourceNode/loop": {},
  "/AudioBufferSourceNode/loopEnd": {},
  "/AudioBufferSourceNode/looping": { "deprecated": true },
  "/AudioBufferSourceNode/loopStart": {},
  "/AudioBufferSourceNode/noteGrainOn": { "deprecated": true },
  "/AudioBufferSourceNode/noteOff": { "deprecated": true },
  "/AudioBufferSourceNode/noteOn": { "deprecated": true },
  "/AudioBufferSourceNode/onended": {},
  "/AudioBufferSourceNode/playbackRate": {},
  "/AudioBufferSourceNode/playbackState": { "deprecated": true },
  "/AudioBufferSourceNode/start": {},
  "/AudioBufferSourceNode/stop": {},

  "/MediaElementAudioSourceNode": { "global": "MediaElementAudioSourceNode", "protected": true },
  "/MediaElementAudioSourceNode/mediaElement": {},

  "/ScriptProcessorNode": { "global": "ScriptProcessorNode", "protected": true },
  "/ScriptProcessorNode/bufferSize": {},
  "/ScriptProcessorNode/onaudioprocess": {},

  "/PannerNode": { "global": false, "protected": true },
  "/PannerNode/EQUALPOWER": { "deprecated": true },
  "/PannerNode/EXPONENTIAL_DISTANCE": { "deprecated": true },
  "/PannerNode/HRTF": { "deprecated": true },
  "/PannerNode/INVERSE_DISTANCE": { "deprecated": true },
  "/PannerNode/LINEAR_DISTANCE": { "deprecated": true },
  "/PannerNode/SOUNDFIELD": { "deprecated": true },
  "/PannerNode/coneInnerAngle": {},
  "/PannerNode/coneOuterAngle": {},
  "/PannerNode/coneOuterGain": {},
  "/PannerNode/distanceModel": {},
  "/PannerNode/maxDistance": {},
  "/PannerNode/panningModel": {},
  "/PannerNode/refDistance": {},
  "/PannerNode/rolloffFactor": {},
  "/PannerNode/setOrientation": {},
  "/PannerNode/setPosition": {},
  "/PannerNode/setVelocity": { "deprecated": true },

  "/AudioListener": { "global": "AudioListener", "protected": true },
  "/AudioListener/dopplerFactor": { "deprecated": true },
  "/AudioListener/setOrientation": {},
  "/AudioListener/setPosition": {},
  "/AudioListener/setVelocity": { "deprecated": true },
  "/AudioListener/speedOfSound": { "deprecated": true },

  "/ConvolverNode": { "global": "ConvolverNode", "protected": true },
  "/ConvolverNode/buffer": {},
  "/ConvolverNode/normalize": {},

  "/AnalyserNode": { "global": "AnalyserNode", "protected": true },
  "/AnalyserNode/fftSize": {},
  "/AnalyserNode/frequencyBinCount": {},
  "/AnalyserNode/getByteFrequencyData": {},
  "/AnalyserNode/getByteTimeDomainData": {},
  "/AnalyserNode/getFloatFrequencyData": {},
  "/AnalyserNode/maxDecibels": {},
  "/AnalyserNode/minDecibels": {},
  "/AnalyserNode/smoothingTimeConstant": {},

  "/ChannelSplitterNode": { "global": "ChannelSplitterNode", "protected": true },

  "/ChannelMergerNode": { "global": "ChannelMergerNode", "protected": true },

  "/DynamicsCompressorNode": { "global": "DynamicsCompressorNode", "protected": true },
  "/DynamicsCompressorNode/attack": {},
  "/DynamicsCompressorNode/knee": {},
  "/DynamicsCompressorNode/ratio": {},
  "/DynamicsCompressorNode/reduction": { "AudioParam": true },
  "/DynamicsCompressorNode/release": {},
  "/DynamicsCompressorNode/threshold": {},

  "/BiquadFilterNode": { "global": "BiquadFilterNode", "protected": true },
  "/BiquadFilterNode/ALLPASS": { "deprecated": true },
  "/BiquadFilterNode/BANDPASS": { "deprecated": true },
  "/BiquadFilterNode/HIGHPASS": { "deprecated": true },
  "/BiquadFilterNode/HIGHSHELF": { "deprecated": true },
  "/BiquadFilterNode/LOWPASS": { "deprecated": true },
  "/BiquadFilterNode/LOWSHELF": { "deprecated": true },
  "/BiquadFilterNode/NOTCH": { "deprecated": true },
  "/BiquadFilterNode/PEAKING": { "deprecated": true },
  "/BiquadFilterNode/detune": {},
  "/BiquadFilterNode/frequency": {},
  "/BiquadFilterNode/gain": {},
  "/BiquadFilterNode/getFrequencyResponse": {},
  "/BiquadFilterNode/Q": {},
  "/BiquadFilterNode/type": {},

  "/WaveShaperNode": { "global": "WaveShaperNode", "protected": true },
  "/WaveShaperNode/curve": {},
  "/WaveShaperNode/oversample": {},

  "/OscillatorNode": { "global": "OscillatorNode", "protected": true },
  "/OscillatorNode/CUSTOM": { "deprecated": true },
  "/OscillatorNode/FINISHED_STATE": { "deprecated": true },
  "/OscillatorNode/PLAYING_STATE": { "deprecated": true },
  "/OscillatorNode/SAWTOOTH": { "deprecated": true },
  "/OscillatorNode/SCHEDULED_STATE": { "deprecated": true },
  "/OscillatorNode/SINE": { "deprecated": true },
  "/OscillatorNode/SQUARE": { "deprecated": true },
  "/OscillatorNode/TRIANGLE": { "deprecated": true },
  "/OscillatorNode/UNSCHEDULED_STATE": { "deprecated": true },
  "/OscillatorNode/detune": {},
  "/OscillatorNode/frequency": {},
  "/OscillatorNode/noteOff": { "deprecated": true },
  "/OscillatorNode/noteOn": { "deprecated": true },
  "/OscillatorNode/onended": { "deprecated": true },
  "/OscillatorNode/playbackState": { "deprecated": true },
  "/OscillatorNode/setPeriodicWave": {},
  "/OscillatorNode/start": {},
  "/OscillatorNode/stop": {},
  "/OscillatorNode/type": {},

  "/PeriodicWave": { "global": "PeriodicWave", "protected": true }
};

module.exports = { name, spec };
