"use strict";

const fullName = "safari:10";

const apiSpec = {
  "/AudioContext": { "global": "webkitAudioContext" },
  "/AudioContext/activeSourceCount": {},
  "/AudioContext/close": {},
  "/AudioContext/createAnalyser": {},
  "/AudioContext/createBiquadFilter": {},
  "/AudioContext/createBuffer": {},
  "/AudioContext/createBufferSource": {},
  "/AudioContext/createChannelMerger": {},
  "/AudioContext/createChannelSplitter": {},
  "/AudioContext/createConvolver": {},
  "/AudioContext/createDelay": {},
  "/AudioContext/createDelayNode": {},
  "/AudioContext/createDynamicsCompressor": {},
  "/AudioContext/createGain": {},
  "/AudioContext/createGainNode": {},
  "/AudioContext/createJavaScriptNode": {},
  "/AudioContext/createMediaElementSource": {},
  "/AudioContext/createOscillator": {},
  "/AudioContext/createPanner": {},
  "/AudioContext/createPeriodicWave": {},
  "/AudioContext/createScriptProcessor": {},
  "/AudioContext/createWaveShaper": {},
  "/AudioContext/currentTime": {},
  "/AudioContext/decodeAudioData": { "void": true },
  "/AudioContext/destination": {},
  "/AudioContext/listener": {},
  "/AudioContext/oncomplete": {},
  "/AudioContext/onstatechange": {},
  "/AudioContext/resume": {},
  "/AudioContext/sampleRate": {},
  "/AudioContext/startRendering": { "void": true },
  "/AudioContext/state": {},
  "/AudioContext/suspend": {},

  "/OfflineAudioContext": { "global": "webkitOfflineAudioContext" },

  "/AudioNode": { "global": "AudioNode" },
  "/AudioNode/channelCount": {},
  "/AudioNode/channelCountMode": {},
  "/AudioNode/channelInterpretation": {},
  "/AudioNode/connect": { "void": true },
  "/AudioNode/context": {},
  "/AudioNode/disconnect": {},
  "/AudioNode/numberOfInputs": {},
  "/AudioNode/numberOfOutputs": {},

  "/AudioDestinationNode": { "global": "AudioDestinationNode" },
  "/AudioDestinationNode/maxChannelCount": {},

  "/AudioParam": { "global": "AudioParam" },
  "/AudioParam/cancelScheduledValues": { "void": true },
  "/AudioParam/defaultValue": {},
  "/AudioParam/exponentialRampToValueAtTime": { "void": true },
  "/AudioParam/linearRampToValueAtTime": { "void": true },
  "/AudioParam/maxValue": {},
  "/AudioParam/minValue": {},
  "/AudioParam/name": {},
  "/AudioParam/setTargetAtTime": { "void": true },
  "/AudioParam/setTargetValueAtTime": { "void": true },
  "/AudioParam/setValueAtTime": { "void": true },
  "/AudioParam/setValueCurveAtTime": { "void": true },
  "/AudioParam/units": {},
  "/AudioParam/value": {},

  "/GainNode": { "global": "GainNode" },
  "/GainNode/gain": {},

  "/DelayNode": { "global": "DelayNode" },
  "/DelayNode/delayTime": {},

  "/AudioBuffer": { "global": "AudioBuffer" },
  "/AudioBuffer/duration": {},
  "/AudioBuffer/gain": {},
  "/AudioBuffer/getChannelData": {},
  "/AudioBuffer/length": {},
  "/AudioBuffer/numberOfChannels": {},
  "/AudioBuffer/sampleRate": {},

  "/AudioBufferSourceNode": { "global": "AudioBufferSourceNode" },
  "/AudioBufferSourceNode/FINISHED_STATE": {},
  "/AudioBufferSourceNode/PLAYING_STATE": {},
  "/AudioBufferSourceNode/SCHEDULED_STATE": {},
  "/AudioBufferSourceNode/UNSCHEDULED_STATE": {},
  "/AudioBufferSourceNode/buffer": {},
  "/AudioBufferSourceNode/gain": {},
  "/AudioBufferSourceNode/loop": {},
  "/AudioBufferSourceNode/loopEnd": {},
  "/AudioBufferSourceNode/looping": {},
  "/AudioBufferSourceNode/loopStart": {},
  "/AudioBufferSourceNode/noteGrainOn": {},
  "/AudioBufferSourceNode/noteOff": {},
  "/AudioBufferSourceNode/noteOn": {},
  "/AudioBufferSourceNode/onended": {},
  "/AudioBufferSourceNode/playbackRate": {},
  "/AudioBufferSourceNode/playbackState": {},
  "/AudioBufferSourceNode/start": {},
  "/AudioBufferSourceNode/stop": {},

  "/MediaElementAudioSourceNode": { "global": "MediaElementAudioSourceNode" },
  "/MediaElementAudioSourceNode/mediaElement": {},

  "/ScriptProcessorNode": { "global": "ScriptProcessorNode" },
  "/ScriptProcessorNode/bufferSize": {},
  "/ScriptProcessorNode/onaudioprocess": {},

  "/PannerNode": { "global": false },
  "/PannerNode/EQUALPOWER": {},
  "/PannerNode/EXPONENTIAL_DISTANCE": {},
  "/PannerNode/HRTF": {},
  "/PannerNode/INVERSE_DISTANCE": {},
  "/PannerNode/LINEAR_DISTANCE": {},
  "/PannerNode/SOUNDFIELD": {},
  "/PannerNode/coneInnerAngle": {},
  "/PannerNode/coneOuterAngle": {},
  "/PannerNode/coneOuterGain": {},
  "/PannerNode/distanceModel": {},
  "/PannerNode/maxDistance": {},
  "/PannerNode/panningModel": {},
  "/PannerNode/refDistance": {},
  "/PannerNode/rolloffFactor": {},
  "/PannerNode/setOrientation": {},
  "/PannerNode/setPosition": {},
  "/PannerNode/setVelocity": {},

  "/AudioListener": { "global": "AudioListener" },
  "/AudioListener/dopplerFactor": {},
  "/AudioListener/setOrientation": {},
  "/AudioListener/setPosition": {},
  "/AudioListener/setVelocity": {},
  "/AudioListener/speedOfSound": {},

  "/ConvolverNode": { "global": "ConvolverNode" },
  "/ConvolverNode/buffer": {},
  "/ConvolverNode/normalize": {},

  "/AnalyserNode": { "global": "AnalyserNode" },
  "/AnalyserNode/fftSize": {},
  "/AnalyserNode/frequencyBinCount": {},
  "/AnalyserNode/getByteFrequencyData": {},
  "/AnalyserNode/getByteTimeDomainData": {},
  "/AnalyserNode/getFloatFrequencyData": {},
  "/AnalyserNode/maxDecibels": {},
  "/AnalyserNode/minDecibels": {},
  "/AnalyserNode/smoothingTimeConstant": {},

  "/ChannelSplitterNode": { "global": "ChannelSplitterNode" },

  "/ChannelMergerNode": { "global": "ChannelMergerNode" },

  "/DynamicsCompressorNode": { "global": "DynamicsCompressorNode" },
  "/DynamicsCompressorNode/attack": {},
  "/DynamicsCompressorNode/knee": {},
  "/DynamicsCompressorNode/ratio": {},
  "/DynamicsCompressorNode/reduction": { "AudioParam": true },
  "/DynamicsCompressorNode/release": {},
  "/DynamicsCompressorNode/threshold": {},

  "/BiquadFilterNode": { "global": "BiquadFilterNode" },
  "/BiquadFilterNode/ALLPASS": {},
  "/BiquadFilterNode/BANDPASS": {},
  "/BiquadFilterNode/HIGHPASS": {},
  "/BiquadFilterNode/HIGHSHELF": {},
  "/BiquadFilterNode/LOWPASS": {},
  "/BiquadFilterNode/LOWSHELF": {},
  "/BiquadFilterNode/NOTCH": {},
  "/BiquadFilterNode/PEAKING": {},
  "/BiquadFilterNode/detune": {},
  "/BiquadFilterNode/frequency": {},
  "/BiquadFilterNode/gain": {},
  "/BiquadFilterNode/getFrequencyResponse": {},
  "/BiquadFilterNode/Q": {},
  "/BiquadFilterNode/type": {},

  "/WaveShaperNode": { "global": "WaveShaperNode" },
  "/WaveShaperNode/curve": {},
  "/WaveShaperNode/oversample": {},

  "/OscillatorNode": { "global": "OscillatorNode" },
  "/OscillatorNode/CUSTOM": {},
  "/OscillatorNode/FINISHED_STATE": {},
  "/OscillatorNode/PLAYING_STATE": {},
  "/OscillatorNode/SAWTOOTH": {},
  "/OscillatorNode/SCHEDULED_STATE": {},
  "/OscillatorNode/SINE": {},
  "/OscillatorNode/SQUARE": {},
  "/OscillatorNode/TRIANGLE": {},
  "/OscillatorNode/UNSCHEDULED_STATE": {},
  "/OscillatorNode/detune": {},
  "/OscillatorNode/frequency": {},
  "/OscillatorNode/noteOff": {},
  "/OscillatorNode/noteOn": {},
  "/OscillatorNode/onended": {},
  "/OscillatorNode/playbackState": {},
  "/OscillatorNode/setPeriodicWave": {},
  "/OscillatorNode/start": {},
  "/OscillatorNode/stop": {},
  "/OscillatorNode/type": {},

  "/PeriodicWave": { "global": "PeriodicWave" }
};

module.exports = { fullName, apiSpec };
