"use strict";

const name = "spec:201512";

const spec = {
  "/BaseAudioContext": { "global": false, "protected": true },
  "/BaseAudioContext/close": {},
  "/BaseAudioContext/createAnalyser": {},
  "/BaseAudioContext/createAudioWorker": {},
  "/BaseAudioContext/createBiquadFilter": {},
  "/BaseAudioContext/createBuffer": {},
  "/BaseAudioContext/createBufferSource": {},
  "/BaseAudioContext/createChannelMerger": {},
  "/BaseAudioContext/createChannelSplitter": {},
  "/BaseAudioContext/createConvolver": {},
  "/BaseAudioContext/createDelay": {},
  "/BaseAudioContext/createDynamicsCompressor": {},
  "/BaseAudioContext/createGain": {},
  "/BaseAudioContext/createIIRFilter": {},
  "/BaseAudioContext/createOscillator": {},
  "/BaseAudioContext/createPanner": {},
  "/BaseAudioContext/createPeriodicWave": {},
  "/BaseAudioContext/createScriptProcessor": {},
  "/BaseAudioContext/createSpatialPanner": {},
  "/BaseAudioContext/createStereoPanner": {},
  "/BaseAudioContext/createWaveShaper": {},
  "/BaseAudioContext/currentTime": {},
  "/BaseAudioContext/decodeAudioData": {},
  "/BaseAudioContext/destination": {},
  "/BaseAudioContext/listener": {},
  "/BaseAudioContext/onstatechange": {},
  "/BaseAudioContext/resume": {},
  "/BaseAudioContext/sampleRate": {},
  "/BaseAudioContext/state": {},
  "/BaseAudioContext/suspend": {},

  "/AudioContext": { "global": "AudioContext" },
  "/AudioContext/createMediaElementSource": {},
  "/AudioContext/createMediaStreamDestination": {},
  "/AudioContext/createMediaStreamSource": {},

  "/OfflineAudioContext": { "global": "OfflineAudioContext" },
  "/OfflineAudioContext/oncomplete": {},
  "/OfflineAudioContext/resume": {},
  "/OfflineAudioContext/startRendering": {},
  "/OfflineAudioContext/suspend": {},

  "/AudioNode": { "global": "AudioNode", "protected": true },
  "/AudioNode/channelCount": {},
  "/AudioNode/channelCountMode": {},
  "/AudioNode/channelInterpretation": {},
  "/AudioNode/connect": {},
  "/AudioNode/context": {},
  "/AudioNode/disconnect": {},
  "/AudioNode/numberOfInputs": {},
  "/AudioNode/numberOfOutputs": {},

  "/AudioDestinationNode": { "global": "AudioDestinationNode", "protected": true },
  "/AudioDestinationNode/maxChannelCount": {},

  "/AudioParam": { "global": "AudioParam", "protected": true },
  "/AudioParam/cancelScheduledValues": {},
  "/AudioParam/defaultValue": {},
  "/AudioParam/exponentialRampToValueAtTime": {},
  "/AudioParam/linearRampToValueAtTime": {},
  "/AudioParam/setTargetAtTime": {},
  "/AudioParam/setValueAtTime": {},
  "/AudioParam/setValueCurveAtTime": {},
  "/AudioParam/value": {},

  "/GainNode": { "global": "GainNode", "protected": true },
  "/GainNode/gain": {},

  "/DelayNode": { "global": "DelayNode", "protected": true },
  "/DelayNode/delayTime": {},

  "/AudioBuffer": { "global": "AudioBuffer", "protected": true },
  "/AudioBuffer/copyFromChannel": {},
  "/AudioBuffer/copyToChannel": {},
  "/AudioBuffer/duration": {},
  "/AudioBuffer/getChannelData": {},
  "/AudioBuffer/length": {},
  "/AudioBuffer/numberOfChannels": {},
  "/AudioBuffer/sampleRate": {},

  "/AudioBufferSourceNode": { "global": "AudioBufferSourceNode", "protected": true },
  "/AudioBufferSourceNode/buffer": {},
  "/AudioBufferSourceNode/detune": {},
  "/AudioBufferSourceNode/loop": {},
  "/AudioBufferSourceNode/loopEnd": {},
  "/AudioBufferSourceNode/loopStart": {},
  "/AudioBufferSourceNode/onended": {},
  "/AudioBufferSourceNode/playbackRate": {},
  "/AudioBufferSourceNode/start": {},
  "/AudioBufferSourceNode/stop": {},

  "/MediaElementAudioSourceNode": { "global": "MediaElementAudioSourceNode", "protected": true },

  "/AudioWorker": { "global": "AudioWorker", "protected": true },
  "/AudioWorker/addParameter": {},
  "/AudioWorker/createNode": {},
  "/AudioWorker/onloaded": {},
  "/AudioWorker/onmessage": {},
  "/AudioWorker/parameters": {},
  "/AudioWorker/postMessage": {},
  "/AudioWorker/removeParameter": {},
  "/AudioWorker/terminate": {},

  "/AudioWorkerNode": { "global": "AudioWorkerNode", "protected": true },
  "/AudioWorkerNode/onmessage": {},
  "/AudioWorkerNode/postMessage": {},

  "/ScriptProcessorNode": { "global": "ScriptProcessorNode", "protected": true },
  "/ScriptProcessorNode/bufferSize": {},
  "/ScriptProcessorNode/onaudioprocess": {},

  "/PannerNode": { "global": "PannerNode", "protected": true },
  "/PannerNode/coneInnerAngle": {},
  "/PannerNode/coneOuterAngle": {},
  "/PannerNode/coneOuterGain": {},
  "/PannerNode/distanceModel": {},
  "/PannerNode/maxDistance": {},
  "/PannerNode/panningModel": {},
  "/PannerNode/refDistance": {},
  "/PannerNode/rolloffFactor": {},
  "/PannerNode/setOrientation": {},
  "/PannerNode/setPosition": {},
  "/PannerNode/setVelocity": {},

  "/AudioListener": { "global": "AudioListener", "protected": true },
  "/AudioListener/setOrientation": {},
  "/AudioListener/setPosition": {},

  "/SpatialPannerNode": { "global": "SpatialPannerNode", "protected": true },
  "/SpatialPannerNode/coneInnerAngle": {},
  "/SpatialPannerNode/coneOuterAngle": {},
  "/SpatialPannerNode/coneOuterGain": {},
  "/SpatialPannerNode/distanceModel": {},
  "/SpatialPannerNode/maxDistance": {},
  "/SpatialPannerNode/orientationX": {},
  "/SpatialPannerNode/orientationY": {},
  "/SpatialPannerNode/orientationZ": {},
  "/SpatialPannerNode/panningModel": {},
  "/SpatialPannerNode/positionX": {},
  "/SpatialPannerNode/positionY": {},
  "/SpatialPannerNode/positionZ": {},
  "/SpatialPannerNode/refDistance": {},
  "/SpatialPannerNode/rolloffFactor": {},

  "/SpatialListener": { "global": "SpatialListener", "protected": true },
  "/SpatialListener/forwardX": {},
  "/SpatialListener/forwardY": {},
  "/SpatialListener/forwardZ": {},
  "/SpatialListener/positionX": {},
  "/SpatialListener/positionY": {},
  "/SpatialListener/positionZ": {},
  "/SpatialListener/upX": {},
  "/SpatialListener/upY": {},
  "/SpatialListener/upZ": {},

  "/StereoPannerNode": { "global": "StereoPannerNode", "protected": true },
  "/StereoPannerNode/pan": {},

  "/ConvolverNode": { "global": "ConvolverNode", "protected": true },
  "/ConvolverNode/buffer": {},
  "/ConvolverNode/normalize": {},

  "/AnalyserNode": { "global": "AnalyserNode", "protected": true },
  "/AnalyserNode/fftSize": {},
  "/AnalyserNode/frequencyBinCount": {},
  "/AnalyserNode/getByteFrequencyData": {},
  "/AnalyserNode/getByteTimeDomainData": {},
  "/AnalyserNode/getFloatFrequencyData": {},
  "/AnalyserNode/getFloatTimeDomainData": {},
  "/AnalyserNode/maxDecibels": {},
  "/AnalyserNode/minDecibels": {},
  "/AnalyserNode/smoothingTimeConstant": {},

  "/ChannelSplitterNode": { "global": "ChannelSplitterNode", "protected": true },

  "/ChannelMergerNode": { "global": "ChannelMergerNode", "protected": true },

  "/DynamicsCompressorNode": { "global": "DynamicsCompressorNode", "protected": true },
  "/DynamicsCompressorNode/attack": {},
  "/DynamicsCompressorNode/knee": {},
  "/DynamicsCompressorNode/ratio": {},
  "/DynamicsCompressorNode/reduction": {},
  "/DynamicsCompressorNode/release": {},
  "/DynamicsCompressorNode/threshold": {},

  "/BiquadFilterNode": { "global": "BiquadFilterNode", "protected": true },
  "/BiquadFilterNode/detune": {},
  "/BiquadFilterNode/frequency": {},
  "/BiquadFilterNode/gain": {},
  "/BiquadFilterNode/getFrequencyResponse": {},
  "/BiquadFilterNode/Q": {},
  "/BiquadFilterNode/type": {},

  "/IIRFilterNode": { "global": "IIRFilterNode", "protected": true },
  "/IIRFilterNode/getFrequencyResponse": {},

  "/WaveShaperNode": { "global": "WaveShaperNode", "protected": true },
  "/WaveShaperNode/curve": {},
  "/WaveShaperNode/oversample": {},

  "/OscillatorNode": { "global": "OscillatorNode", "protected": true },
  "/OscillatorNode/detune": {},
  "/OscillatorNode/frequency": {},
  "/OscillatorNode/onended": {},
  "/OscillatorNode/setPeriodicWave": {},
  "/OscillatorNode/start": {},
  "/OscillatorNode/stop": {},
  "/OscillatorNode/type": {},

  "/PeriodicWave": { "global": "PeriodicWave", "protected": true },

  "/MediaStreamAudioSourceNode": { "global": "MediaStreamAudioSourceNode", "protected": true },

  "/MediaStreamAudioDestinationNode": { "global": "MediaStreamAudioDestinationNode", "protected": true },
  "/MediaStreamAudioDestinationNode/stream": {}
};

module.exports = { name, spec };
