"use strict";

const name = "spec:201208";

const apiSpec = {
  "/AudioContext": { "global": "AudioContext" },
  "/AudioContext/activeSourceCount": {},
  "/AudioContext/createAnalyser": {},
  "/AudioContext/createBiquadFilter": {},
  "/AudioContext/createBuffer": { "mixToMono": true },
  "/AudioContext/createBufferSource": {},
  "/AudioContext/createChannelMerger": {},
  "/AudioContext/createChannelSplitter": {},
  "/AudioContext/createConvolver": {},
  "/AudioContext/createDelayNode": {},
  "/AudioContext/createDynamicsCompressor": {},
  "/AudioContext/createGainNode": {},
  "/AudioContext/createJavaScriptNode": {},
  "/AudioContext/createMediaElementSource": {},
  "/AudioContext/createMediaStreamSource": {},
  "/AudioContext/createOscillator": {},
  "/AudioContext/createPanner": {},
  "/AudioContext/createWaveTable": {},
  "/AudioContext/currentTime": {},
  "/AudioContext/decodeAudioData": { "void": true },
  "/AudioContext/destination": {},
  "/AudioContext/listener": {},
  "/AudioContext/sampleRate": {},

  "/AudioNode": { "global": "AudioNode", "constructor": "illegal" },
  "/AudioNode/connect": { "void": true },
  "/AudioNode/context": {},
  "/AudioNode/disconnect": {},
  "/AudioNode/numberOfInputs": {},
  "/AudioNode/numberOfOutputs": {},

  "/AudioSourceNode": { "global": "AudioSourceNode", "constructor": "illegal" },

  "/AudioDestinationNode": { "global": "AudioDestinationNode", "constructor": "illegal" },
  "/AudioDestinationNode/maxChannelCount": {},
  "/AudioDestinationNode/numberOfChannels": {},

  "/AudioParam": { "global": "AudioParam", "constructor": "illegal" },
  "/AudioParam/cancelScheduledValues": { "void": true },
  "/AudioParam/defaultValue": {},
  "/AudioParam/exponentialRampToValueAtTime": { "void": true },
  "/AudioParam/linearRampToValueAtTime": { "void": true },
  "/AudioParam/maxValue": {},
  "/AudioParam/minValue": {},
  "/AudioParam/setTargetValueAtTime": { "void": true },
  "/AudioParam/setValueAtTime": { "void": true },
  "/AudioParam/setValueCurveAtTime": { "void": true },
  "/AudioParam/value": {},

  "/GainNode": { "global": "AudioGainNode", "constructor": "illegal" },
  "/GainNode/gain": {},

  "/DelayNode": { "global": "DelayNode", "constructor": "illegal" },
  "/DelayNode/delayTime": {},

  "/AudioBuffer": { "global": "AudioBuffer", "constructor": "illegal" },
  "/AudioBuffer/duration": {},
  "/AudioBuffer/getChannelData": {},
  "/AudioBuffer/length": {},
  "/AudioBuffer/numberOfChannels": {},
  "/AudioBuffer/sampleRate": {},

  "/AudioBufferSourceNode": { "global": "AudioBufferSourceNode", "constructor": "illegal" },
  "/AudioBufferSourceNode/FINISHED_STATE": {},
  "/AudioBufferSourceNode/PLAYING_STATE": {},
  "/AudioBufferSourceNode/SCHEDULED_STATE": {},
  "/AudioBufferSourceNode/UNSCHEDULED_STATE": {},
  "/AudioBufferSourceNode/buffer": {},
  "/AudioBufferSourceNode/loop": {},
  "/AudioBufferSourceNode/noteGrainOn": {},
  "/AudioBufferSourceNode/noteOff": {},
  "/AudioBufferSourceNode/noteOn": {},
  "/AudioBufferSourceNode/playbackRate": {},
  "/AudioBufferSourceNode/playbackState": {},

  "/MediaElementAudioSourceNode": { "global": "MediaElementAudioSourceNode", "constructor": "illegal" },

  "/ScriptProcessorNode": { "global": "JavaScriptAudioNode", "constructor": "illegal" },
  "/ScriptProcessorNode/bufferSize": {},
  "/ScriptProcessorNode/onaudioprocess": {},

  "/PannerNode": { "global": "AudioPannerNode", "constructor": "illegal" },
  "/PannerNode/EQUALPOWER": {},
  "/PannerNode/EXPONENTIAL_DISTANCE": {},
  "/PannerNode/HRTF": {},
  "/PannerNode/INVERSE_DISTANCE": {},
  "/PannerNode/LINEAR_DISTANCE": {},
  "/PannerNode/SOUNDFIELD": {},
  "/PannerNode/coneGain": {},
  "/PannerNode/coneInnerAngle": {},
  "/PannerNode/coneOuterAngle": {},
  "/PannerNode/coneOuterGain": {},
  "/PannerNode/distanceGain": {},
  "/PannerNode/distanceModel": {},
  "/PannerNode/maxDistance": {},
  "/PannerNode/panningModel": {},
  "/PannerNode/refDistance": {},
  "/PannerNode/rolloffFactor": {},
  "/PannerNode/setOrientation": {},
  "/PannerNode/setPosition": {},
  "/PannerNode/setVelocity": {},

  "/AudioListener": { "global": "AudioListener", "constructor": "illegal" },
  "/AudioListener/dopplerFactor": {},
  "/AudioListener/setOrientation": {},
  "/AudioListener/setPosition": {},
  "/AudioListener/setVelocity": {},
  "/AudioListener/speedOfSound": {},

  "/ConvolverNode": { "global": "ConvolverNode", "constructor": "illegal" },
  "/ConvolverNode/buffer": {},
  "/ConvolverNode/normalize": {},

  "/AnalyserNode": { "global": "RealtimeAnalyserNode", "constructor": "illegal" },
  "/AnalyserNode/fftSize": {},
  "/AnalyserNode/frequencyBinCount": {},
  "/AnalyserNode/getByteFrequencyData": {},
  "/AnalyserNode/getByteTimeDomainData": {},
  "/AnalyserNode/getFloatFrequencyData": {},
  "/AnalyserNode/maxDecibels": {},
  "/AnalyserNode/minDecibels": {},
  "/AnalyserNode/smoothingTimeConstant": {},

  "/ChannelSplitterNode": { "global": "AudioChannelSplitter", "constructor": "illegal" },

  "/ChannelMergerNode": { "global": "AudioChannelMerger", "constructor": "illegal" },

  "/DynamicsCompressorNode": { "global": "DynamicsCompressorNode", "constructor": "illegal" },
  "/DynamicsCompressorNode/attack": {},
  "/DynamicsCompressorNode/knee": {},
  "/DynamicsCompressorNode/ratio": {},
  "/DynamicsCompressorNode/reduction": { "AudioParam": true },
  "/DynamicsCompressorNode/release": {},
  "/DynamicsCompressorNode/threshold": {},

  "/BiquadFilterNode": { "global": "BiquadFilterNode", "constructor": "illegal" },
  "/BiquadFilterNode/ALLPASS": {},
  "/BiquadFilterNode/BANDPASS": {},
  "/BiquadFilterNode/HIGHPASS": {},
  "/BiquadFilterNode/HIGHSHELF": {},
  "/BiquadFilterNode/LOWPASS": {},
  "/BiquadFilterNode/LOWSHELF": {},
  "/BiquadFilterNode/NOTCH": {},
  "/BiquadFilterNode/PEAKING": {},
  "/BiquadFilterNode/frequency": {},
  "/BiquadFilterNode/gain": {},
  "/BiquadFilterNode/getFrequencyResponse": {},
  "/BiquadFilterNode/Q": {},
  "/BiquadFilterNode/type": {},

  "/WaveShaperNode": { "global": "WaveShaperNode", "constructor": "illegal" },
  "/WaveShaperNode/curve": {},

  "/OscillatorNode": { "global": "Oscillator", "constructor": "illegal" },
  "/OscillatorNode/CUSTOM": {},
  "/OscillatorNode/FINISHED_STATE": {},
  "/OscillatorNode/PLAYING_STATE": {},
  "/OscillatorNode/SAWTOOTH": {},
  "/OscillatorNode/SCHEDULED_STATE": {},
  "/OscillatorNode/SINE": {},
  "/OscillatorNode/SQUARE": {},
  "/OscillatorNode/TRIANGLE": {},
  "/OscillatorNode/UNSCHEDULED_STATE": {},
  "/OscillatorNode/detune": {},
  "/OscillatorNode/frequency": {},
  "/OscillatorNode/noteOff": {},
  "/OscillatorNode/noteOn": {},
  "/OscillatorNode/playbackState": {},
  "/OscillatorNode/setWaveTable": {},
  "/OscillatorNode/type": {},

  "/PeriodicWave": { "global": "WaveTable", "constructor": "illegal" },

  "/MediaStreamAudioSourceNode": { "global": "MediaStreamAudioSourceNode" }
};

module.exports = { name, apiSpec };
